# Generated by Django 4.2.19 on 2025-03-03 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='autor',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='foto_producto',
            field=models.ImageField(default='productos/default.svg', upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='link_producto',
            field=models.URLField(default=''),
        ),
        migrations.CreateModel(
            name='FotoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='autores/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='proyectos.autor')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='autores',
            field=models.ManyToManyField(related_name='proyectos', to='proyectos.autor'),
        ),
    ]
