# Generated by Django 4.2.19 on 2025-03-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_autor_remove_proyecto_autor_proyecto_foto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
