# Generated by Django 4.2.19 on 2025-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_proyecto_link_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='autores',
            field=models.ManyToManyField(to='proyectos.autor'),
        ),
    ]
